#!/bin/bash
SOURCE_FILE=$1
##-- https://stackoverflow.com/a/43380040
##-- Posted by peak, modified by community. See post 'Timeline' for change history
##-- Retrieved 2025-11-23, License - CC BY-SA 4.0

jq 'paths(scalars) | map(tostring) | join(".")' $SOURCE_FILE
