#!/bin/bash
source ~/bin/gemini-keys
echo "GEMINI_API_KEY=${GEMINI_API_KEY}" > .env
INPUT=$1
aider --no-auto-commits --no-gitignore --model gemini/gemini-2.5-flash -m "/ask could you generate report based on this transcript in markdown syntax? in 2 sections: (A) 50 single select Quiz questions (B) FAQ (C) Abbreviation (D) Terminology. Thanks." --chat-history-file ${INPUT%.json}.md $INPUT
