#!/bin/bash
INPUT=$1
aider --no-auto-commits --no-gitignore --model gemini/gemini-2.5-flash -m "/ask could you summarize this transcript using markdown syntax? in 3 sections: (A) Overall Summary and Takeaways (B) Detailed summary based on different attendees (C) Action items. capture as much detail as possible. use bullet points. use markdown checkbox syntax for action items. Thanks." --chat-history-file ${INPUT%.json}.md $INPUT
