#!/bin/bash
if [ $# -lt 2 ]; then
  echo "Usage: $0 <NOTEBOOK_ID> <URL>"
  exit 1
fi

NOTEBOOK=$1
URL=$2

SRC_ID=$(nlm source add $NOTEBOOK -y $URL | grep 'Source ID' | awk '{ print $3 }')
nlm report create $NOTEBOOK -y --language zh_TW -s ${SRC_ID}
