#!/bin/bash
if [ "$#" -lt 2 ]; then
    echo "Error: This script requires at least two arguments."
    echo "Usage: $0 <URL> <output_file_name>"
    exit 1
fi
URL=$1
OUTPUT=$2
yt-dlp --write-subs --sub-langs "en" --sub-format json3 --skip-download -o ${OUTPUT} ${URL}
