# -*- coding: utf-8 -*-

## this program will read from a CSV and output prefill Google Form URL
## 這是一個簡單的小程式，用來根據 CSV 欄位裡的數值來產生 Google 表單的預填連結

import csv
import sys
import urllib.parse

## this url_template was manually generated by Google Form and replaced variables with {}
## 這個網址是先使用 Google Form 產生一個範例，拿掉想預先填入的欄位，取代為 {} 後，供 Python String format() 函數使用
url_template = "https://docs.google.com/forms/d/e/1FAIpQLScxin7cEvC-G6TpBTDNS4a3TMWC2IZXJiH_Qel15jdKMQgV-w/viewform?usp=pp_url&entry.246220059={}&entry.510881599={}&entry.136181766={}"

if len(sys.argv) < 2:
    print("Usage: " + sys.argv[0] + " input_file_name.csv")
    sys.exit(1)

input_file_name = sys.argv[1]

with open( input_file_name ,"r") as csvfile:
    reader = csv.DictReader(csvfile)
    
    for row in reader:
        name = row["NAME"]
        name_encoded = urllib.parse.quote(name, encoding="UTF-8")
        id = row["ID"]
        uuid = row["UUID"]
        print(url_template.format(uuid,id,name_encoded))