/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jazz' at '2016/6/1 下午 4:08' with Gradle 2.13
 *
 * @author jazz, @date 2016/6/1 下午 4:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
