# https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-compose

version: '2'
services:
  web:
    image: 'gitlab/gitlab-ee:15.4.0-ee.0'
    restart: always
    hostname: 'docker.3du.me'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://docker.3du.me:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
