version: '2'

services:

  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
