# https://github.com/marketplace/actions/screenshots-ci-action
name: screenshot
on:
  #schedule:
  #  # Runs "" (see https://crontab.guru)
  #  - cron: '30 4 * * 1-5'
  workflow_dispatch:
    inputs:
      url:
        description: 'The website URL (ex: https://www.google.com/)'
        required: true
        default: ''
jobs:
  screenshots:
    runs-on: ubuntu-latest
    # reference:
    # [1] https://github.com/marketplace/actions/get-playwright-version
    # [2] https://mcr.microsoft.com/en-us/artifact/mar/playwright/python/tags
    # container:
    #   image: docker pull mcr.microsoft.com/playwright/python:v1.48.0
    steps:
    # https://playwright.dev/python/docs/ci-intro
    - name: Install pytest-playwright
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright
        python -m playwright install
        python -m playwright install --with-deps
    - name: Capture screenshot
      run: |
        playwright screenshot -b chrome  --viewport-size "2048, 1152" ${{ github.event.inputs.url }} $(date +"%Y-%m-%d_%H%M%S.png")
